### ISSUE TITLE
How to use SSH keys

### ISSUE THREAD

**Issue by brockfanning** [jonaseberle/github-action-setup-ddev#13]
Hi all, what is the suggested way to use install SSH keys (such as from Github secrets)? My instinct was to use "ddev auth ssh" but it is omitted here: https://github.com/jonaseberle/github-action-setup-ddev/blob/master/lib/main.js#L68

I tried using a separate Github action to install the SSH keys after setting up ddev, but that did not work. Eg:

```
steps:
  - uses: actions/checkout@v2
  - name: Set up ddev
    uses: jonaseberle/github-action-setup-ddev@v1
  - name: Set up SSH keys
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.MY_KEY }}
      known_hosts: ${{ secrets.MY_KNOWN_HOSTS }}
  - name: Test remote connection
    run: |
      ddev exec drush @my.alias status
```

I also tried with the ssh-key-action before the github-action-setup-ddev, but no luck there either. Any advice is greatly appreciated!

**Comment by jonaseberle** [comment]
I've never really tried if the ssh-agent would be viable.

I've used keys like that:

```
steps:
  - uses: actions/checkout@v2
  - name: Set up SSH keys
    run: echo "{{ secrets.privateKey }}" > .ddev/homeadditions/.ssh/id_rsa
  - name: Set up ddev
    uses: jonaseberle/github-action-setup-ddev@v1
```
