### ISSUE TITLE
Allow installing a specific ddev version

### ISSUE THREAD

**Issue by jonaseberle** [jonaseberle/github-action-setup-ddev#15]
Especially with things like upcoming breaking ddev release v1.19 I'd not like build pipelines to break.
So I would like to control which ddev version will be installed.

**Comment by hawkeyetwolf** [comment]
When installing via the install script, we can just pass the version we want to install, e.g.,:
```yaml
inputs:
  version:
    description: "Override the DDEV version .e.g. '1.19.0'"
    required: false
```

```sh
# Download and run the DDEV installer
if [ "${{ inputs.version }}" != "" ]; then
  curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh v${{ inputs.version }}
else
  curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
fi
rm -f install_ddev.sh
```
With the current implementation of installing via `apt`, I'm not sure the correct syntax, just figured I'd drop the snippet here in case it's useful :)
