### ISSUE TITLE
Add inputs for SSH keys

### ISSUE THREAD

**Issue by hawkeyetwolf** [jonaseberle/github-action-setup-ddev#30]
Instead of putting the SSH key instructions in the "Common recipes" README documentation, we could make them part of the action.

I'm not sure if this needs to definitely run before `ddev start`, but maybe.

```yaml
inputs:
  ssh-private-key:
    description: "SSH Private Key"
    required: false
  ssh-known-hosts:
    description: "SSH Known Hosts"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up SSH keys
      shell: bash
      run: |
        mkdir -p .ddev/homeadditions/.ssh
        # Copy private key
        if [ "${{ inputs.ssh-private-key }}" != "" ]; then
          echo "${{ inputs.ssh-private-key }}" > .ddev/homeadditions/.ssh/id_rsa
          chmod 600 .ddev/homeadditions/.ssh/id_rsa
        fi
        # Copy known hosts
        if [ "${{ inputs.ssh-known-hosts }}" != "" ]; then
          echo "${{ inputs.ssh-known-hosts}}" > .ddev/homeadditions/.ssh/known_hosts
          chmod 644 .ddev/homeadditions/.ssh/known_hosts
        fi
        chmod 700 .ddev/homeadditions/.ssh
```
