### ISSUE TITLE
Add inputs for git email and name

### ISSUE THREAD

**Issue by hawkeyetwolf** [jonaseberle/github-action-setup-ddev#31]
This is useful when using ddev for deployment actions. Note that this step should run _after_ `ddev start`.
```yaml
inputs:
  git-email:
    description: "Git e-mail address"
    required: false
  git-name:
    description: "Git name"
    required: false
runs:
  using: "composite"
  steps:
    ...
    - name: Configure git credentials
      shell: bash
      run: |
        ddev exec "git config --global user.name \"${{ inputs.git-name }}\""
        ddev exec "git config --global user.email \"${{ inputs.git-email }}\""
```
