### ISSUE TITLE
Set composer cache directory inside ddev web container

### ISSUE THREAD

**Issue by hawkeyetwolf** [jonaseberle/github-action-setup-ddev#32]
Performance improvement. Note that this must run _before_ `ddev start`.
```yaml
inputs:
  ...
  composer-cache-dir:
    description: "Composer cache directory, relative to the project workspace. Set to false to disable."
    required: false
runs:
  using: "composite"
  steps:
    ...
    - name: Set composer cache directory inside ddev web container
      shell: bash
      run: |
        if [ "${{ inputs.composer-cache-dir }}" != "false" ]; then
          # @todo Replace /var/www/html with an environment variable.
          CACHE_DIR=".ddev/.drainpipe-composer-cache"
          if [ "${{ inputs.composer-cache-dir }}" != "" ]; then
            CACHE_DIR="${{ inputs.composer-cache-dir }}"
          fi
          ddev config --web-environment-add="COMPOSER_CACHE_DIR=/var/www/html/$CACHE_DIR"
        fi
```
