### ISSUE TITLE
CI fails due to deprecated add-path when setting up ddev

### ISSUE THREAD

**Issue by nostadt** [jonaseberle/github-action-setup-ddev#4]
My current CI Pipeline fails at this point:

```
Setting up docker-ce (5:19.03.13~3-0~ubuntu-bionic) ...

Processing triggers for libc-bin (2.27-3ubuntu1.3) ...

Processing triggers for systemd (237-3ubuntu10.42) ...

Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

Processing triggers for ureadahead (0.100.0-21) ...

Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
Warning: Linuxbrew has been merged into Homebrew.
Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"


==> This script will install:

/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
```

According to the [linked GitHub Blog entry](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) it has to do something add-path being deprecated and which is to be replaced by Environment Files. I don't see the reason in my `workflow` file. So, I assume it's somewhere in the GitHub Action.

```
name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jonaseberle/github-action-setup-ddev@v1
      - name: Prepare TYPO3
        run: |
          cp private/typo3conf/AdditionalConfiguration.Local.example.php private/typo3conf/AdditionalConfiguration.Local.php
      - name: Install dependencies
        run: ddev composer install
      - name: Run tests from the web
        run: |
          ddev exec "mkdir -p tests/unit/ext/ && cd tests/unit/ext/ && ln -s ../../../packages/ext/Tests/"
          ddev exec vendor/bin/codecept run unit
          ddev exec vendor/bin/codecept run functional
      - name: Run tests from the host
        run: vendor/bin/codecept run acceptance --env firefox --env chrome

```
